return {
  lsp = {
    "clangd",
    "cssls",
    "docker_compose_language_service",
    "dockerls",
    "emmet_ls",
    "gopls",
    "gradle_ls",
    "html",
    "jdtls",
    "jsonls",
    "lua_ls",
    "pylsp",
    "phpactor",
    "rust_analyzer",
    "sqlls",
    "stylelint_lsp",
    "tsserver",
  },
  treesitter = {
    "c",
    "css",
    "dockerfile",
    "go",
    "html",
    "java",
    "javascript",
    "json",
    "lua",
    "python",
    "rust",
    "php",
    "sql",
    "yaml",
  },
  conform = {
    c = { "clang-format" },
    css = { "prettier" },
    go = { "goimports", "gofmt" },
    html = { "prettier" },
    javascript = { "prettier" },
    json = { "jq" },
    lua = { "stylua" },
    php = { "pretty-php" },
    rust = { "rustfmt" },
    sql = { "sql_formatter" },
  },
}
